import { Post, Review, UserNotification, UserProfile } from "../types";

export const INITIAL_USER: UserProfile = {
  id: "user-current-1",
  name: "Алексей Смирнов",
  email: "alexey.nsk@mail.ru",
  phone: "+7 (913) 912-45-78",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
  role: "user",
  rating: 4.92,
  completedOrdersCount: 14,
  responsesCount: 8,
  isPro: false,
  isProPlus: false,
  district: "Октябрьский",
  createdAt: "2024-03-10T10:00:00Z",
  bio: "Живу на Восходе. Ценю честность и пунктуальность соседей.",
  businessDetails: {
    name: "Сибирь-Кофе",
    description: "Уютная спешелти кофейня в Октябрьском районе",
    category: "Кафе",
    address: "ул. Восход, 14/1",
    phone: "+7 (383) 214-55-11",
    schedule: "Ежедневно 07:30 – 21:00",
  },
};

// 10 Urgent Requests («Нужно сейчас»)
export const MOCK_REQUESTS: Post[] = [
  {
    id: "req-1",
    type: "request",
    category: "Электрик",
    title: "Нужен электрик заменить две розетки и выключатель",
    description: "Искрит розетка на кухне и нужно установить двойную розетку под холодильник. Инструментов нет, фурнитура куплена. Нужно сделать сегодня до 20:00.",
    district: "Октябрьский",
    coordinates: [55.0142, 82.9712],
    approxAddress: "ул. Сакко и Ванцетти, район м. Октябрьская",
    price: 2000,
    date: "Сегодня",
    time: "до 20:00",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 34,
    responsesCount: 2,
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    authorId: "u-nsk-101",
    authorName: "Елена В.",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 6,
    authorRole: "user",
  },
  {
    id: "req-2",
    type: "request",
    category: "Перевозка",
    title: "Нужно поднять угловой диван на 5 этаж без грузового лифта",
    description: "Диван разобран на три секции. Нужны двое крепких ребят или один помощник мне. Займет не более 35 минут.",
    district: "Октябрьский",
    coordinates: [55.0084, 82.9691],
    approxAddress: "ул. Большевистская, возле набережной Михайловской",
    price: 2500,
    date: "Сегодня",
    time: "После 18:30",
    urgency: "high",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 52,
    responsesCount: 3,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    authorId: "u-nsk-102",
    authorName: "Максим Громов",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 19,
    authorRole: "user",
  },
  {
    id: "req-3",
    type: "request",
    category: "Сантехник",
    title: "Течет труба под раковиной в ванной срочно",
    description: "Подкапывает сифон или гофра, образовалась лужа. Нужен мастер со своим ремкомплектом устранить течь прямо сейчас.",
    district: "Октябрьский",
    coordinates: [55.0195, 82.9815],
    approxAddress: "ул. Кирова (возле Сибстрин)",
    price: 1800,
    date: "Сегодня",
    time: "Срочно",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 88,
    responsesCount: 4,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    authorId: "u-nsk-103",
    authorName: "Ольга Сергеевна",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.8,
    authorCompletedCount: 11,
    authorRole: "user",
  },
  {
    id: "req-4",
    type: "request",
    category: "Уборка",
    title: "Генеральная уборка 2-комнатной квартиры после съезда",
    description: "Площадь 54 кв.м. Помыть сантехнику, окна изнутри, обеспылить поверхности. Средства для уборки на месте.",
    district: "Центральный",
    coordinates: [55.0321, 82.9189],
    approxAddress: "ул. Советская / пл. Ленина",
    price: 4500,
    date: "Завтра",
    time: "с 10:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 41,
    responsesCount: 1,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-104",
    authorName: "Артем П.",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.95,
    authorCompletedCount: 8,
    authorRole: "user",
  },
  {
    id: "req-5",
    type: "request",
    category: "Сборка мебели",
    title: "Собрать комод и обувницу из Леруа Мерлен",
    description: "Инструкция и вся фурнитура в запечатанной коробке. Шуруповерт желательно свой. Октябрьский район, ориентир ГПНТБ.",
    district: "Октябрьский",
    coordinates: [55.0175, 82.9554],
    approxAddress: "ул. Восход, рядом с ГПНТБ",
    price: 1700,
    date: "Сегодня",
    time: "19:00 – 21:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: false,
    viewsCount: 29,
    responsesCount: 2,
    createdAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    authorId: "u-nsk-105",
    authorName: "Дарья К.",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.7,
    authorCompletedCount: 4,
    authorRole: "user",
  },
  {
    id: "req-6",
    type: "request",
    category: "Авто",
    title: "Прикурить авто на ул. Нижегородской, сел аккумулятор",
    description: "Toyota Corolla, аккумулятор сел от аварийки. Провода есть, нужно подъехать прикурить. Оплата сразу переводом или наличными.",
    district: "Октябрьский",
    coordinates: [55.0162, 82.9498],
    approxAddress: "ул. Нижегородская, парковка у бизнес-центра",
    price: 600,
    date: "Сегодня",
    time: "Прямо сейчас",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 67,
    responsesCount: 1,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    authorId: "u-nsk-106",
    authorName: "Сергей Д.",
    authorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 22,
    authorRole: "user",
  },
  {
    id: "req-7",
    type: "request",
    category: "Забрать/доставить",
    title: "Срочно забрать документы из суда и передать курьеру",
    description: "Забрать готовую выписку в канцелярии Октябрьского районного суда и передать на станцию метро Речной Вокзал.",
    district: "Октябрьский",
    coordinates: [55.0211, 82.9688],
    approxAddress: "Октябрьский районный суд",
    price: 800,
    date: "Сегодня",
    time: "до 16:30",
    urgency: "high",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 38,
    responsesCount: 2,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    authorId: "u-nsk-107",
    authorName: "Юлия Юрьевна",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 30,
    authorRole: "user",
  },
  {
    id: "req-8",
    type: "request",
    category: "Животные",
    title: "Выгулять золотистого ретривера вечером (1 час)",
    description: "Пес очень добрый, приучен к поводку. Задержались на работе, погулять в сквере у ГПНТБ.",
    district: "Октябрьский",
    coordinates: [55.0169, 82.9567],
    approxAddress: "сквер ГПНТБ",
    price: 700,
    date: "Сегодня",
    time: "19:30",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: false,
    viewsCount: 24,
    responsesCount: 1,
    createdAt: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    authorId: "u-nsk-108",
    authorName: "Алина М.",
    authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.85,
    authorCompletedCount: 5,
    authorRole: "user",
  },
  {
    id: "req-9",
    type: "request",
    category: "Компьютер",
    title: "Настроить Wi-Fi роутер и принтер в домашнем офисе",
    description: "Купили Keenetic, не получается подружить с оптическим терминалом Ростелекома. Нужно настроить стабильный интернет и сетевую печать.",
    district: "Заельцовский",
    coordinates: [55.0612, 82.9021],
    approxAddress: "ул. Дуси Ковальчук, район пл. Калинина",
    price: 1500,
    date: "Сегодня",
    time: "В любое время до 22:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 33,
    responsesCount: 3,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-109",
    authorName: "Константин",
    authorAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.6,
    authorCompletedCount: 3,
    authorRole: "user",
  },
  {
    id: "req-10",
    type: "request",
    category: "Помощь с ребёнком",
    title: "Встретить первоклассника из лицея №185 и довести до дома",
    description: "Пройти 400 метров без перехода дорог. Бабушка заболела, мама в пробке на мосту. Обязательно ответственная соседка с отзывами.",
    district: "Октябрьский",
    coordinates: [55.0112, 82.9621],
    approxAddress: "ул. Тургенева, лицей №185",
    price: 500,
    date: "Сегодня",
    time: "в 14:15",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 45,
    responsesCount: 2,
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    authorId: "u-nsk-110",
    authorName: "Екатерина Николаевна",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 14,
    authorRole: "user",
  },
];

// 10 Services / Offers («Я предлагаю» - Услуги)
export const MOCK_OFFERS: Post[] = [
  {
    id: "off-1",
    type: "offer",
    category: "Ремонт",
    title: "Мастер на час: сантехника, электрика, мелкий ремонт",
    description: "Профессиональный инструмент (перфоратор, лазерный уровень, труборез). Опыт 12 лет. Выезжаю по Октябрьскому и Центральному районам за 25 минут.",
    district: "Октябрьский",
    coordinates: [55.0171, 82.9682],
    approxAddress: "ул. Кирова / метро Октябрьская",
    price: 800,
    time: "Ежедневно 8:00–22:00",
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 210,
    responsesCount: 16,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    authorId: "u-exec-1",
    authorName: "Иван Мастеровой",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.98,
    authorCompletedCount: 142,
    authorRole: "executor",
  },
  {
    id: "off-2",
    type: "offer",
    category: "Перевозка",
    title: "Грузоперевозки на Газели Next + 2 аккуратных грузчика",
    description: "Чистый закрытый кузов 4.2 метра. Ремни для фиксации мебели и холодильников. Подача 20 минут в любой район правого берега.",
    district: "Октябрьский",
    coordinates: [55.0098, 82.9782],
    approxAddress: "ул. Выборная / Ключ-Камышенское плато",
    price: 1200,
    time: "Круглосуточно",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: true,
    isVerified: true,
    viewsCount: 145,
    responsesCount: 12,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    authorId: "u-exec-2",
    authorName: "Виктор Транс",
    authorAvatar: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.91,
    authorCompletedCount: 89,
    authorRole: "executor",
  },
  {
    id: "off-3",
    type: "offer",
    category: "Уборка",
    title: "Качественный эко-клининг квартир парогенератором Karcher",
    description: "Уборка без едкой химии, безопасно для детей и аллергиков. Мытье окон, духовок, удаление известкового налета.",
    district: "Центральный",
    coordinates: [55.0298, 82.9234],
    approxAddress: "Красный проспект",
    price: 2200,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 98,
    responsesCount: 9,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    authorId: "u-exec-3",
    authorName: "Анна Клининг",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 47,
    authorRole: "executor",
  },
  {
    id: "off-4",
    type: "offer",
    category: "Компьютер",
    title: "Срочный ремонт ноутбуков и ПК на дому, чистка от пыли",
    description: "Замена термопасты Arctic MX-4, установка SSD без потери данных, удаление вирусов, настройка роутеров. Выезд без оплаты диагностики.",
    district: "Октябрьский",
    coordinates: [55.0182, 82.9641],
    approxAddress: "ул. Восход, 5",
    price: 900,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 167,
    responsesCount: 14,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    authorId: "u-exec-4",
    authorName: "Дмитрий Чип",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.88,
    authorCompletedCount: 63,
    authorRole: "executor",
  },
  {
    id: "off-5",
    type: "offer",
    category: "Авто",
    title: "Отогрев авто тепловой пушкой + прикуривание 12/24V",
    description: "Бережный запуск двигателей в мороз, прокалка свечей, подзарядка АКБ. Дежурю в районе Большевистской и Речного вокзала.",
    district: "Октябрьский",
    coordinates: [55.0062, 82.9612],
    approxAddress: "Речной вокзал / Большевистская",
    price: 1500,
    time: "Круглосуточно",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 124,
    responsesCount: 11,
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    authorId: "u-exec-5",
    authorName: "Роман Автопомощь",
    authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.96,
    authorCompletedCount: 78,
    authorRole: "executor",
  },
  {
    id: "off-6",
    type: "offer",
    category: "Животные",
    title: "Догситтер и выгул собак в парках Октябрьского района",
    description: "Кинологическое образование, опыт с крупными и тревожными собаками. Фотоотчеты с каждой прогулки, мытье лап.",
    district: "Октябрьский",
    coordinates: [55.0155, 82.9577],
    approxAddress: "сквер ГПНТБ / ул. Восход",
    price: 500,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 82,
    responsesCount: 7,
    createdAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    authorId: "u-exec-6",
    authorName: "Мария Зоо",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 39,
    authorRole: "executor",
  },
  {
    id: "off-7",
    type: "offer",
    category: "Сборка мебели",
    title: "Сборка шкафов-купе, кухонь и офисной мебели любой сложности",
    description: "Вырезы под мойку и варочную панель, регулировка петель, подвес полок и телевизоров на кронштейн.",
    district: "Ленинский",
    coordinates: [54.9862, 82.8712],
    approxAddress: "пл. Карла Маркса",
    price: 1000,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: false,
    viewsCount: 74,
    responsesCount: 5,
    createdAt: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    authorId: "u-exec-7",
    authorName: "Евгений Сборщик",
    authorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.82,
    authorCompletedCount: 34,
    authorRole: "executor",
  },
  {
    id: "off-8",
    type: "offer",
    category: "Сантехник",
    title: "Устранение засоров гидродинамикой, замена смесителей, разводка труб",
    description: "Трубы полипропилен, сшитый полиэтилен Rehau. Установка радиаторов отопления и водонагревателей.",
    district: "Заельцовский",
    coordinates: [55.0645, 82.9011],
    approxAddress: "метро Заельцовская",
    price: 1200,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: true,
    isVerified: true,
    viewsCount: 112,
    responsesCount: 10,
    createdAt: new Date(Date.now() - 9 * 3600 * 1000).toISOString(),
    authorId: "u-exec-8",
    authorName: "Сергей Сантех",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.94,
    authorCompletedCount: 92,
    authorRole: "executor",
  },
  {
    id: "off-9",
    type: "offer",
    category: "Помощь с ребёнком",
    title: "Автоняня: безопасная доставка детей в школы и секции",
    description: "Автомобиль Toyota RAV4 с сертифицированными креслами Isofix. Стаж безаварийного вождения 16 лет. Передаю лично тренеру или учителю.",
    district: "Советский",
    coordinates: [54.8512, 83.0912],
    approxAddress: "Морской проспект, Академгородок",
    price: 600,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 138,
    responsesCount: 8,
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    authorId: "u-exec-9",
    authorName: "Наталья Ивановна",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 65,
    authorRole: "executor",
  },
  {
    id: "off-10",
    type: "offer",
    category: "Другое",
    title: "Заточка ножей, ножниц и цепей бензопил на станке Tormek",
    description: "Японский угол заточки до бритвенной остроты. Забираю и возвращаю по району при заказе от 3 предметов.",
    district: "Октябрьский",
    coordinates: [55.0134, 82.9734],
    approxAddress: "ул. Бориса Богаткова",
    price: 350,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 64,
    responsesCount: 4,
    createdAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    authorId: "u-exec-10",
    authorName: "Александр Точильщик",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.87,
    authorCompletedCount: 28,
    authorRole: "executor",
  },
];

// 10 Local Deals («Выгодно рядом»)
export const MOCK_DEALS: Post[] = [
  {
    id: "deal-1",
    type: "deal",
    category: "Кафе",
    title: "Свежий кофе + миндальный круассан со скидкой 30%",
    description: "Утренний комбо-сет с 8:00 до 12:00. Зерно свежей обжарки (Эфиопия Иргачефф), круассаны выпекаем каждые два часа.",
    district: "Октябрьский",
    coordinates: [55.0165, 82.9698],
    approxAddress: "ул. Восход, 14/1",
    price: 299,
    originalPrice: 430,
    discountPercent: 30,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 312,
    responsesCount: 28,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    authorId: "biz-1",
    authorName: "Сибирь-Кофе",
    authorAvatar: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.96,
    authorCompletedCount: 240,
    authorRole: "business",
    businessName: "Сибирь-Кофе Roasters",
    businessAddress: "ул. Восход, 14/1 (вход со стороны метро)",
    businessPhone: "+7 (383) 214-55-11",
    businessSchedule: "Пн-Вс: 07:30 – 21:00",
  },
  {
    id: "deal-2",
    type: "deal",
    category: "Еда",
    title: "Римская пицца «4 Сыра» навынос со скидкой −20%",
    description: "Хрустящее воздушное тесто созревания 48 часов, сыры Моцарелла, Горгонзола, Пармезан и Скаморца.",
    district: "Октябрьский",
    coordinates: [55.0199, 82.9721],
    approxAddress: "ул. Сакко и Ванцетти, 25",
    price: 590,
    originalPrice: 740,
    discountPercent: 20,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 289,
    responsesCount: 19,
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    authorId: "biz-2",
    authorName: "Пиццерия «Bella Napoli»",
    authorAvatar: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.92,
    authorCompletedCount: 310,
    authorRole: "business",
    businessName: "Bella Napoli Trattoria",
    businessAddress: "ул. Сакко и Ванцетти, 25",
    businessPhone: "+7 (383) 304-80-00",
    businessSchedule: "11:00 – 23:00",
  },
  {
    id: "deal-3",
    type: "deal",
    category: "Красота",
    title: "Мужская стрижка + моделирование бороды за 1 290 ₽",
    description: "Знакомство с барбером. Мытье головы с массажем, укладка премиум-пастой Morgan's и холодный напиток в подарок.",
    district: "Октябрьский",
    coordinates: [55.0145, 82.9654],
    approxAddress: "ул. Кирова, 44/2",
    price: 1290,
    originalPrice: 1800,
    discountPercent: 28,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: true,
    isVerified: true,
    viewsCount: 194,
    responsesCount: 15,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    authorId: "biz-3",
    authorName: "Barbershop «Сибирский Медведь»",
    authorAvatar: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.88,
    authorCompletedCount: 180,
    authorRole: "business",
    businessName: "Барбершоп Сибирский Медведь",
    businessAddress: "ул. Кирова, 44/2",
    businessPhone: "+7 (383) 299-12-34",
    businessSchedule: "10:00 – 22:00",
  },
  {
    id: "deal-4",
    type: "deal",
    category: "Авто",
    title: "Комплексная мойка кузова и ковриков + воск за 750 ₽",
    description: "Трехфазная нано-мойка, сушка турбосушкой без разводов. Для жителей Октябрьского района по промокоду «РЯДОМ».",
    district: "Октябрьский",
    coordinates: [55.0089, 82.9745],
    approxAddress: "ул. Большевистская, 177 к2",
    price: 750,
    originalPrice: 1100,
    discountPercent: 32,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 165,
    responsesCount: 22,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    authorId: "biz-4",
    authorName: "Автомойка Aquagroom",
    authorAvatar: "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.75,
    authorCompletedCount: 130,
    authorRole: "business",
    businessName: "Автокомплекс Aquagroom",
    businessAddress: "ул. Большевистская, 177 к2",
    businessPhone: "+7 (913) 777-11-22",
  },
  {
    id: "deal-5",
    type: "deal",
    category: "Спорт",
    title: "Пробная тренировка в фитнес-клубе + сауна за 300 ₽",
    description: "Тренажерный зал 1200 кв.м с видом на Обь, зона единоборств и финская сауна. Без скрытых платежей.",
    district: "Октябрьский",
    coordinates: [55.0115, 82.9599],
    approxAddress: "ул. Обская, 2 (Европейский берег)",
    price: 300,
    originalPrice: 900,
    discountPercent: 67,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 240,
    responsesCount: 31,
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    authorId: "biz-5",
    authorName: "Фитнес RiverFit",
    authorAvatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.95,
    authorCompletedCount: 350,
    authorRole: "business",
    businessName: "RiverFit Club",
    businessAddress: "Европейский берег, ул. Обская, 2",
    businessPhone: "+7 (383) 380-00-11",
  },
  {
    id: "deal-6",
    type: "deal",
    category: "Магазины",
    title: "Свежая фермерская форель со скидкой −25% до конца недели",
    description: "Прямая поставка с алтайского форелевого хозяйства. Охлажденная рыба, бесплатная чистка при покупке от 1 шт.",
    district: "Центральный",
    coordinates: [55.0345, 82.9211],
    approxAddress: "Центральный рынок, павильон 4",
    price: 890,
    originalPrice: 1190,
    discountPercent: 25,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 178,
    responsesCount: 14,
    createdAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    authorId: "biz-6",
    authorName: "Рыбная Лавка Сибири",
    authorAvatar: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.89,
    authorCompletedCount: 88,
    authorRole: "business",
  },
  {
    id: "deal-7",
    type: "deal",
    category: "Дети",
    title: "День в батутном парке для детей за 490 ₽ вместо 800 ₽",
    description: "Безлимитное время в будние дни. 24 батута, поролоновая яма и стена для скалолазания под присмотром инструктора.",
    district: "Кировский",
    coordinates: [54.9654, 82.9265],
    approxAddress: "ул. Ватутина, ТРЦ МЕГА",
    price: 490,
    originalPrice: 800,
    discountPercent: 39,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 132,
    responsesCount: 17,
    createdAt: new Date(Date.now() - 15 * 3600 * 1000).toISOString(),
    authorId: "biz-7",
    authorName: "Парк «Высота НСК»",
    authorAvatar: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.82,
    authorCompletedCount: 120,
    authorRole: "business",
  },
  {
    id: "deal-8",
    type: "deal",
    category: "Услуги",
    title: "Химчистка пуховика или зимнего пальто со скидкой −20%",
    description: "Итальянские эко-препараты, бережное удаление пятен от реагентов и засаленностей. Срок готовности 48 часов.",
    district: "Октябрьский",
    coordinates: [55.0151, 82.9645],
    approxAddress: "ул. Бориса Богаткова, 208",
    price: 1200,
    originalPrice: 1500,
    discountPercent: 20,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 89,
    responsesCount: 8,
    createdAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    authorId: "biz-8",
    authorName: "Химчистка «Диана-Сибирь»",
    authorAvatar: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.79,
    authorCompletedCount: 95,
    authorRole: "business",
  },
  {
    id: "deal-9",
    type: "deal",
    category: "Развлечения",
    title: "Квиз «Огни Новосибирска» для команды: 5-й игрок бесплатно",
    description: "Интеллектуальная игра в пабе с призами и крафтовыми напитками. Четверг 19:30. Забронируйте столик по акции.",
    district: "Центральный",
    coordinates: [55.0289, 82.9245],
    approxAddress: "ул. Ленина, 12",
    price: 400,
    originalPrice: 500,
    discountPercent: 20,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 205,
    responsesCount: 24,
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    authorId: "biz-9",
    authorName: "Quiz Novosibirsk",
    authorAvatar: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.97,
    authorCompletedCount: 420,
    authorRole: "business",
  },
  {
    id: "deal-10",
    type: "deal",
    category: "Кафе",
    title: "Бизнес-ланч: суп дня + горячее + морс за 360 ₽",
    description: "Домашняя сибирская кухня: борщ с говядиной, котлета из щуки с картофельным пюре и брусничный морс.",
    district: "Октябрьский",
    coordinates: [55.0185, 82.9701],
    approxAddress: "ул. Восход, 26/1",
    price: 360,
    originalPrice: 480,
    discountPercent: 25,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 147,
    responsesCount: 18,
    createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    authorId: "biz-10",
    authorName: "Кафе «Брусника»",
    authorAvatar: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.84,
    authorCompletedCount: 160,
    authorRole: "business",
  },
];

// 10 Events («События рядом»)
export const MOCK_EVENTS: Post[] = [
  {
    id: "ev-1",
    type: "event",
    category: "Городские",
    title: "Вечер джаза на Михайловской набережной у Оби",
    description: "Открытый живой концерт новосибирского джазового квинтета на сцене у колеса обозрения. Берите пледы и горячий чай!",
    district: "Октябрьский",
    coordinates: [55.0078, 82.9645],
    approxAddress: "Михайловская набережная, главная сцена",
    price: 0,
    date: "Сегодня",
    time: "19:00",
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 410,
    responsesCount: 52,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    authorId: "org-1",
    authorName: "Дирекция парков Новосибирска",
    authorAvatar: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.95,
    authorCompletedCount: 80,
    authorRole: "business",
    externalUrl: "https://parki-nsk.ru",
  },
  {
    id: "ev-2",
    type: "event",
    category: "Мастер-классы",
    title: "Гончарный мастер-класс: лепка кружки своими руками",
    description: "Камерная группа до 6 человек. Обожжем в печи и покроем пищевой глазурью. Готовое изделие можно забрать через 5 дней.",
    district: "Октябрьский",
    coordinates: [55.0162, 82.9678],
    approxAddress: "ул. Восход, 3 (арт-пространство «Студия 14»)",
    price: 1600,
    date: "Завтра",
    time: "18:30",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: true,
    isVerified: true,
    viewsCount: 180,
    responsesCount: 14,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    authorId: "org-2",
    authorName: "Керамика «Глина & Огонь»",
    authorAvatar: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 65,
    authorRole: "business",
  },
  {
    id: "ev-3",
    type: "event",
    category: "Выставки",
    title: "Фотовыставка «Старый Новониколаевск: улицы и мосты»",
    description: "Уникальные архивные фотографии 1893–1930 годов из фондов краеведческого музея. Бесплатная экскурсия для гостей в 17:00.",
    district: "Октябрьский",
    coordinates: [55.0178, 82.9562],
    approxAddress: "ГПНТБ СО РАН, 2 этаж",
    price: 0,
    date: "Сегодня и завтра",
    time: "11:00 – 19:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 260,
    responsesCount: 21,
    createdAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    authorId: "org-3",
    authorName: "ГПНТБ СО РАН",
    authorAvatar: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 40,
    authorRole: "user",
    externalUrl: "https://www.spsl.nsc.ru",
  },
  {
    id: "ev-4",
    type: "event",
    category: "Спорт",
    title: "Открытая пробежка с разминкой по набережной (5 км)",
    description: "Беговой клуб «Беги, НСК!». Темп спокойный (6:00–6:30 мин/км), новички приветствуются. Встречаемся у памятника Первому мосту.",
    district: "Октябрьский",
    coordinates: [55.0065, 82.9632],
    approxAddress: "Парк «Городское начало», памятник Александру III",
    price: 0,
    date: "Суббота",
    time: "09:00",
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 215,
    responsesCount: 38,
    createdAt: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
    authorId: "org-4",
    authorName: "Беговой клуб «Беги, НСК!»",
    authorAvatar: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.98,
    authorCompletedCount: 110,
    authorRole: "user",
  },
  {
    id: "ev-5",
    type: "event",
    category: "Детские",
    title: "Интерактивный научный спектакль «Тайна жидкого азота»",
    description: "Опыты с заморозкой фруктов, взрывы мыльной пены и лазерное шоу. Для детей от 5 до 12 лет. Каждому ребенку сувенир.",
    district: "Центральный",
    coordinates: [55.0315, 82.9254],
    approxAddress: "ул. Фрунзе, 5, театр юного зрителя",
    price: 650,
    date: "Воскресенье",
    time: "12:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: true,
    isVerified: true,
    viewsCount: 175,
    responsesCount: 18,
    createdAt: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
    authorId: "org-5",
    authorName: "Научный театр «WOW-Lab»",
    authorAvatar: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.88,
    authorCompletedCount: 45,
    authorRole: "business",
  },
  {
    id: "ev-6",
    type: "event",
    category: "Ярмарки",
    title: "Сибирская ярмарка крафта и локальных сыроделов",
    description: "Сыры из козьего и коровьего молока из Ордынского и Сузунского районов, мед, кедровые орехи, изделия из бересты и глины.",
    district: "Октябрьский",
    coordinates: [55.0182, 82.9575],
    approxAddress: "площадь Пименова перед ГПНТБ",
    price: 0,
    date: "Выходные",
    time: "10:00 – 18:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 340,
    responsesCount: 29,
    createdAt: new Date(Date.now() - 21 * 3600 * 1000).toISOString(),
    authorId: "org-6",
    authorName: "Ассоциация фермеров НСО",
    authorAvatar: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 35,
    authorRole: "business",
  },
  {
    id: "ev-7",
    type: "event",
    category: "Концерты",
    title: "Акустический вечер инди-рока в клубе «Труба»",
    description: "Новосибирские группы «Черная речка» и «Перемотка» с акустической программой. Атмосферный свет и живой звук.",
    district: "Центральный",
    coordinates: [55.0275, 82.9198],
    approxAddress: "ул. Ленина, 15",
    price: 700,
    date: "Пятница",
    time: "20:00",
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: true,
    isVerified: true,
    viewsCount: 290,
    responsesCount: 34,
    createdAt: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    authorId: "org-7",
    authorName: "Арт-клуб «Труба»",
    authorAvatar: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.93,
    authorCompletedCount: 210,
    authorRole: "business",
  },
  {
    id: "ev-8",
    type: "event",
    category: "Бесплатные",
    title: "Уличная астрономическая площадка: смотрим на Юпитер и Луну",
    description: "Новосибирское астрономическое общество выставляет три мощных телескопа. Лекция о созвездиях весеннего неба при ясной погоде.",
    district: "Заельцовский",
    coordinates: [55.0712, 82.8945],
    approxAddress: "Заельцовский парк, центральная поляна",
    price: 0,
    date: "Сегодня",
    time: "21:30",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 380,
    responsesCount: 46,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    authorId: "org-8",
    authorName: "Большой Новосибирский планетарий",
    authorAvatar: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 95,
    authorRole: "business",
    externalUrl: "https://nebo-nsk.ru",
  },
  {
    id: "ev-9",
    type: "event",
    category: "Мастер-классы",
    title: "Воркшоп по приготовлению сибирских настоек на травах",
    description: "Разбор трав Салаирского кряжа (сагаан-дайля, чабрец, кедровый стланик). Каждый участник приготовит свой купаж 0.5 л.",
    district: "Октябрьский",
    coordinates: [55.0191, 82.9715],
    approxAddress: "ул. Сакко и Ванцетти, 31",
    price: 1800,
    date: "Суббота",
    time: "17:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 145,
    responsesCount: 11,
    createdAt: new Date(Date.now() - 29 * 3600 * 1000).toISOString(),
    authorId: "org-9",
    authorName: "Барная школа НСК",
    authorAvatar: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.87,
    authorCompletedCount: 30,
    authorRole: "business",
  },
  {
    id: "ev-10",
    type: "event",
    category: "Городские",
    title: "Велопрогулка по Академгородку: секретные тропы ученых",
    description: "Маршрут 12 км от Технопарка до пляжа Обского моря через тропы институтов СО РАН. Шлем обязателен.",
    district: "Советский",
    coordinates: [54.8562, 83.1045],
    approxAddress: "Академгородок, башни Технопарка (ул. Николаева, 12)",
    price: 0,
    date: "Воскресенье",
    time: "11:00",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 220,
    responsesCount: 27,
    createdAt: new Date(Date.now() - 33 * 3600 * 1000).toISOString(),
    authorId: "org-10",
    authorName: "АкадемВело",
    authorAvatar: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.96,
    authorCompletedCount: 74,
    authorRole: "user",
  },
];

// 10 Announcements («Объявления рядом»)
export const MOCK_ANNOUNCEMENTS: Post[] = [
  {
    id: "ann-1",
    type: "neighbor",
    category: "Отдам",
    title: "Отдам детскую деревянную кроватку с матрасом",
    description: "Состояние отличное, массив березы, регулируемое дно. Ребенок вырос. Самовывоз с 3 этажа, помогу спустить к машине.",
    district: "Октябрьский",
    coordinates: [55.0152, 82.9723],
    approxAddress: "ул. Бориса Богаткова, 194",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 95,
    responsesCount: 6,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-201",
    authorName: "Марина К.",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 15,
    authorRole: "user",
  },
  {
    id: "ann-2",
    type: "neighbor",
    category: "Найдено",
    title: "Найдены ключи от автомобиля Kia с брелоком StarLine",
    description: "На скамейке в сквере перед ГПНТБ сегодня около 11:30 утра. Отдам владельцу при нажатии на брелок или совпадении ключа.",
    district: "Октябрьский",
    coordinates: [55.0171, 82.9568],
    approxAddress: "сквер ГПНТБ, центральная аллея",
    price: 0,
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 140,
    responsesCount: 4,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    authorId: "u-nsk-202",
    authorName: "Денис Панов",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 9,
    authorRole: "user",
  },
  {
    id: "ann-3",
    type: "neighbor",
    category: "Потеряно",
    title: "Потерялся рыжий кот породы мейн-кун (откликается на Рыжик)",
    description: "Выскочил из открытой двери в подъезде дома по ул. Кирова 27. Ошейник с адресником. Вознаграждение нашедшему 10 000 ₽!",
    district: "Октябрьский",
    coordinates: [55.0198, 82.9685],
    approxAddress: "ул. Кирова, 27 / ул. Ипподромская",
    price: 10000,
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 310,
    responsesCount: 12,
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    authorId: "u-nsk-203",
    authorName: "Светлана Р.",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 7,
    authorRole: "user",
  },
  {
    id: "ann-4",
    type: "neighbor",
    category: "Помощь",
    title: "Могу помочь донести тяжелые сумки или вещи пожилым соседям",
    description: "Каждый вечер после 19:00 дома в Октябрьском районе. Абсолютно бесплатно, по-соседски. Пишите!",
    district: "Октябрьский",
    coordinates: [55.0141, 82.9691],
    approxAddress: "ул. Сакко и Ванцетти",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 88,
    responsesCount: 5,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-204",
    authorName: "Илья Добрый",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 21,
    authorRole: "user",
  },
  {
    id: "ann-5",
    type: "neighbor",
    category: "Отдам",
    title: "Отдам плотные картонные коробки для переезда (15 штук)",
    description: "Чистые, пятислойный картон, размер 60х40х40. Жалко выбрасывать. Забирайте возле метро Октябрьская.",
    district: "Октябрьский",
    coordinates: [55.0181, 82.9655],
    approxAddress: "ул. Шевченко, 15",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: false,
    viewsCount: 73,
    responsesCount: 8,
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-205",
    authorName: "Артем С.",
    authorAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.8,
    authorCompletedCount: 6,
    authorRole: "user",
  },
  {
    id: "ann-6",
    type: "neighbor",
    category: "Продам",
    title: "Детский велосипед Shulz Bubble 16 в отличном состоянии",
    description: "Легкий алюминиевый, вес всего 6.8 кг. Катались один сезон в парке. В комплекте звонок и крылья.",
    district: "Октябрьский",
    coordinates: [55.0118, 82.9605],
    approxAddress: "Европейский берег, ул. Большевистская",
    price: 9500,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 115,
    responsesCount: 3,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-206",
    authorName: "Ольга В.",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.95,
    authorCompletedCount: 12,
    authorRole: "user",
  },
  {
    id: "ann-7",
    type: "neighbor",
    category: "Куплю",
    title: "Куплю остатки фасадного керамогранита или кафеля 2-3 кв.м",
    description: "Не хватило буквально 6 плиток серого оттенка 60х60 для прихожей. Заберу сам сегодня на правом берегу.",
    district: "Октябрьский",
    coordinates: [55.0165, 82.9782],
    approxAddress: "ул. Ленинградская",
    price: 1500,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: false,
    viewsCount: 42,
    responsesCount: 2,
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-207",
    authorName: "Григорий",
    authorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.7,
    authorCompletedCount: 3,
    authorRole: "user",
  },
  {
    id: "ann-8",
    type: "neighbor",
    category: "Животные",
    title: "Отдам в добрые руки очаровательного шотландского вислоухого котенка",
    description: "Возраст 2.5 месяца. Приучен к лотку и когтеточке, кушает сухой корм премиум. Очень ласковый мурлыка.",
    district: "Центральный",
    coordinates: [55.0312, 82.9195],
    approxAddress: "ул. Романова, 39",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 230,
    responsesCount: 14,
    createdAt: new Date(Date.now() - 19 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-208",
    authorName: "Татьяна",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 18,
    authorRole: "user",
  },
  {
    id: "ann-9",
    type: "neighbor",
    category: "Разное",
    title: "Кто знает хорошего честного автомеханика по Toyota в нашем районе?",
    description: "Нужно поменять сайлентблоки и стойки стабилизатора. Посоветуйте проверенный сервис или частника без накруток.",
    district: "Октябрьский",
    coordinates: [55.0135, 82.9699],
    approxAddress: "ул. Автогенная",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 84,
    responsesCount: 9,
    createdAt: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-209",
    authorName: "Василий",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.88,
    authorCompletedCount: 10,
    authorRole: "user",
  },
  {
    id: "ann-10",
    type: "neighbor",
    category: "Отдам",
    title: "Отдам коллекцию книг по программированию и дизайну",
    description: "JavaScript, React, типографика, книги Артемия Лебедева. 12 увесистых томов. Самовывоз с ул. Восход.",
    district: "Октябрьский",
    coordinates: [55.0169, 82.9642],
    approxAddress: "ул. Восход, 7",
    price: 0,
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 160,
    responsesCount: 11,
    createdAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-210",
    authorName: "Сергей Разработчик",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.95,
    authorCompletedCount: 25,
    authorRole: "user",
  },
];

// 5 Important Local Alerts («Важно рядом»)
export const MOCK_ALERTS: Post[] = [
  {
    id: "alert-1",
    type: "alert",
    category: "Перекрытие дорог",
    title: "Временное сужение ул. Большевистской в районе Речного вокзала",
    description: "В связи с ремонтом теплотрассы перекрыты две крайние правые полосы по направлению к центру. Пробка 6 баллов. Выбирайте пути объезда через ул. Кирова или Ипподромскую.",
    district: "Октябрьский",
    coordinates: [55.0095, 82.9641],
    approxAddress: "ул. Большевистская, 12, около развязки с Октябрьским мостом",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 650,
    responsesCount: 14,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    authorId: "city-alert-1",
    authorName: "ЦОДД Новосибирск",
    authorAvatar: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 500,
    authorRole: "business",
    time: "до 20:00 завтра",
  },
  {
    id: "alert-2",
    type: "alert",
    category: "Отключение воды",
    title: "Плановое отключение горячей воды в микрорайоне Закаменский",
    description: "СГК проводит гидравлические испытания тепловых сетей зоны ТЭЦ-5. Отключение затронет дома по ул. Кирова, Сакко и Ванцетти, Нижегородской.",
    district: "Октябрьский",
    coordinates: [55.0212, 82.9734],
    approxAddress: "ул. Кирова / ул. Бориса Богаткова",
    urgency: "normal",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 520,
    responsesCount: 8,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    authorId: "city-alert-2",
    authorName: "СГК Новосибирск (Оперативный штаб)",
    authorAvatar: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.8,
    authorCompletedCount: 410,
    authorRole: "business",
    time: "с 14 по 19 число",
  },
  {
    id: "alert-3",
    type: "alert",
    category: "Авария",
    title: "ДТП с участием фуры на перекрестке Восход и Зыряновской",
    description: "Заблокировано трамвайное движение маршрутов №13 и №14 в сторону ГПНТБ. На месте работают сотрудники ГИБДД и аварийный комиссар.",
    district: "Октябрьский",
    coordinates: [55.0158, 82.9621],
    approxAddress: "перекресток ул. Восход и Зыряновской",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 430,
    responsesCount: 19,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    authorId: "u-nsk-301",
    authorName: "АСТ-54 (Сообщество очевидцев)",
    authorAvatar: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=120&auto=format&fit=crop&q=80",
    authorRating: 4.9,
    authorCompletedCount: 280,
    authorRole: "user",
    time: "15 минут назад",
  },
  {
    id: "alert-4",
    type: "alert",
    category: "Опасный участок",
    title: "Гололедица и наледь на лестнице спуска к метро Октябрьская",
    description: "Будьте предельно осторожны при спуске со стороны сквера им. Крячкова. Ступени обледенели, коммунальные службы вызваны.",
    district: "Октябрьский",
    coordinates: [55.0185, 82.9671],
    approxAddress: "спуск к ст. м. Октябрьская (выход №2)",
    urgency: "high",
    status: "active",
    isBoosted: false,
    isPro: false,
    isVerified: true,
    viewsCount: 390,
    responsesCount: 11,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    authorId: "u-nsk-302",
    authorName: "Ирина (житель дома №25)",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 15,
    authorRole: "user",
  },
  {
    id: "alert-5",
    type: "alert",
    category: "Городское предупреждение",
    title: "Штормовое предупреждение: усиление ветра до 22 м/с в Новосибирске",
    description: "МЧС предупреждает: ожидается шквалистый ветер, метель и гололедица. Не паркуйте автомобили под ветхими деревьями и рекламными щитами.",
    district: "Октябрьский",
    coordinates: [55.0188, 82.9734],
    approxAddress: "по всему городу и акватории Оби",
    urgency: "high",
    status: "active",
    isBoosted: true,
    isPro: false,
    isVerified: true,
    viewsCount: 890,
    responsesCount: 22,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    authorId: "city-mchs",
    authorName: "ГУ МЧС по Новосибирской области",
    authorAvatar: "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=120&auto=format&fit=crop&q=80",
    authorRating: 5.0,
    authorCompletedCount: 999,
    authorRole: "business",
    time: "на сутки вперед",
  },
];

export const ALL_INITIAL_POSTS: Post[] = [
  ...MOCK_REQUESTS,
  ...MOCK_OFFERS,
  ...MOCK_DEALS,
  ...MOCK_EVENTS,
  ...MOCK_ANNOUNCEMENTS,
  ...MOCK_ALERTS,
];

export const INITIAL_NOTIFICATIONS: UserNotification[] = [
  {
    id: "notif-1",
    userId: "user-current-1",
    type: "urgent_request",
    title: "🆘 Новый срочный запрос рядом",
    message: "В 450 м на ул. Сакко и Ванцетти срочно нужен электрик — 2 000 ₽",
    postId: "req-1",
    district: "Октябрьский",
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-current-1",
    type: "deal",
    title: "🛍 Новая скидка рядом с вами",
    message: "Кофейня «Сибирь-Кофе» в 600 м предлагает комбо за 299 ₽ (−30%)",
    postId: "deal-1",
    district: "Октябрьский",
    isRead: false,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-current-1",
    type: "alert",
    title: "⚠️ Внимание: ограничение движения",
    message: "Сужение ул. Большевистской у Речного вокзала, ремонт теплотрассы",
    postId: "alert-1",
    district: "Октябрьский",
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: "notif-4",
    userId: "user-current-1",
    type: "response",
    title: "❤️ На ваш запрос откликнулся мастер",
    message: "Иван Мастеровой готов выполнить работу сегодня в 19:00",
    postId: "req-1",
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    targetUserId: "user-current-1",
    authorId: "u-rev-1",
    authorName: "Елена В.",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Очень выручил! Быстро пришел, помог поднять тяжелую коробку и закрутить винты. Приятный вежливый сосед.",
    createdAt: "2025-01-20T14:30:00Z",
  },
  {
    id: "rev-2",
    targetUserId: "user-current-1",
    authorId: "u-rev-2",
    authorName: "Михаил Андреев",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Все точно вовремя, как и договаривались. Большое спасибо за отзывчивость!",
    createdAt: "2025-02-04T18:10:00Z",
  },
];
